-- MySQL Script generated by MySQL Workbench
-- 05/02/16 22:56:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlinvestdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlinvestdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `controlinvestdb` ;

-- -----------------------------------------------------
-- Table `controlinvestdb`.`investidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlinvestdb`.`investidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `totalinvestido` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlinvestdb`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlinvestdb`.`objetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `objetivocol` TEXT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `valoratual` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlinvestdb`.`investimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlinvestdb`.`investimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `investidor_id` INT NOT NULL,
  `objetivo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_investimento_investidor_idx` (`investidor_id` ASC),
  INDEX `fk_investimento_objetivo1_idx` (`objetivo_id` ASC),
  CONSTRAINT `fk_investimento_investidor`
    FOREIGN KEY (`investidor_id`)
    REFERENCES `controlinvestdb`.`investidor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investimento_objetivo1`
    FOREIGN KEY (`objetivo_id`)
    REFERENCES `controlinvestdb`.`objetivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
